### PR TITLE
Added panic orders

### PR DESCRIPTION
**Pull request by salipshitz**

### CODE REVIEW

**Comment by ethanent** [comment]
Right, thanks!

Here is a thought - what if instead of nearly copying the sell command code, we call the cmdSell function? We can pass along custom arguments to the function after finding the quantity owned by the user.

**Comment by salipshitz** [comment]
Maybe. I could do that 2moro

**Comment by salipshitz** [comment]
I did it. Check now

**Comment by ethanent** [comment]
Great, thanks for the feature addition. :)

**Pull request merged**
